// Mock venue database for demo purposes
export interface Venue {
  id: string;
  name: string;
  email?: string;
  location: string;
  city: string;
  capacity: number;
  pricing: {
    min: number;
    max: number;
    description: string;
  };
  hasAccommodation: boolean;
  accommodationRooms?: number;
  hasOutdoorSpace: boolean;
  cateringOptions: 'in-house' | 'external' | 'both';
  cateringTypes: string[]; // halal, kosher, vegetarian, vegan, etc.
  amenities: string[];
  aesthetic: string[]; // rustic, modern, traditional, barn, manor, garden
  notes: string;
  images?: string[];
  status?: 'not_contacted' | 'contacted' | 'responded' | 'complete' | 'needs_follow_up' | 'rejected';
  lastUpdated?: Date;
  responseData?: any;
}

export const MOCK_VENUES: Venue[] = [
  {
    id: '1',
    name: 'Cliveden House',
    email: 'weddings@clivedenhouse.co.uk',
    location: 'Taplow, Berkshire',
    city: 'Berkshire',
    capacity: 120,
    pricing: { min: 12000, max: 25000, description: '£12,000 - £25,000 (exclusive use)' },
    hasAccommodation: true,
    accommodationRooms: 38,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['halal', 'kosher', 'vegetarian', 'vegan', 'gluten-free'],
    amenities: ['Licensed for ceremonies', 'Exclusive use', 'Spa', 'River views', 'Gardens', 'Parking', 'Bridal suite'],
    aesthetic: ['manor', 'traditional', 'luxury'],
    notes: 'Historic 5-star luxury hotel with stunning Thames views and 376 acres of grounds',
    status: 'not_contacted'
  },
  {
    id: '2',
    name: 'The Barn at Bury Court',
    location: 'Bentley, Surrey',
    city: 'Surrey',
    capacity: 150,
    pricing: { min: 8000, max: 15000, description: '£8,000 - £15,000 (venue hire + catering)' },
    hasAccommodation: false,
    hasOutdoorSpace: true,
    cateringOptions: 'both',
    cateringTypes: ['vegetarian', 'vegan', 'halal'],
    amenities: ['Licensed for ceremonies', 'Gardens', 'Parking for 100', 'Bar facilities', 'Vintage furniture'],
    aesthetic: ['rustic', 'barn', 'garden'],
    notes: 'Beautiful 17th-century barn with walled gardens and rustic charm',
    status: 'not_contacted'
  },
  {
    id: '3',
    name: 'Hedsor House',
    location: 'Taplow, Buckinghamshire',
    city: 'Buckinghamshire',
    capacity: 180,
    pricing: { min: 15000, max: 30000, description: '£15,000 - £30,000 (exclusive use)' },
    hasAccommodation: true,
    accommodationRooms: 12,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['halal', 'kosher', 'vegetarian', 'vegan'],
    amenities: ['Exclusive use', 'Licensed for ceremonies', '100-acre grounds', 'Helipad', 'Cinema room', 'Parking'],
    aesthetic: ['manor', 'luxury', 'traditional'],
    notes: 'Georgian manor house with spectacular Thames Valley views',
    status: 'not_contacted'
  },
  {
    id: '4',
    name: 'Trinity Buoy Wharf',
    location: 'London Docklands',
    city: 'London',
    capacity: 200,
    pricing: { min: 5000, max: 12000, description: '£5,000 - £12,000 (venue hire)' },
    hasAccommodation: false,
    hasOutdoorSpace: true,
    cateringOptions: 'external',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Waterfront location', 'Industrial space', 'Outdoor terrace', 'Parking', 'Unique setting'],
    aesthetic: ['industrial', 'modern', 'urban'],
    notes: 'Unique industrial riverside venue with London skyline views',
    status: 'not_contacted'
  },
  {
    id: '5',
    name: 'Elmore Court',
    location: 'Gloucestershire',
    city: 'Gloucestershire',
    capacity: 140,
    pricing: { min: 10000, max: 18000, description: '£10,000 - £18,000 (exclusive use)' },
    hasAccommodation: true,
    accommodationRooms: 25,
    hasOutdoorSpace: true,
    cateringOptions: 'both',
    cateringTypes: ['halal', 'vegetarian', 'vegan', 'gluten-free'],
    amenities: ['Exclusive use', 'Licensed for ceremonies', 'Treehouse', 'Gardens', 'Parking', 'Bridal cottage'],
    aesthetic: ['manor', 'garden', 'quirky'],
    notes: 'Beautiful country estate with famous treehouse and stunning gardens',
    status: 'not_contacted'
  },
  {
    id: '6',
    name: 'Asylum Chapel',
    location: 'Peckham, London',
    city: 'London',
    capacity: 100,
    pricing: { min: 4000, max: 8000, description: '£4,000 - £8,000 (venue hire)' },
    hasAccommodation: false,
    hasOutdoorSpace: false,
    cateringOptions: 'external',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Historic building', 'Unique character', 'Central London'],
    aesthetic: ['industrial', 'unique', 'urban'],
    notes: 'Grade II listed Victorian chapel with dramatic exposed interior',
    status: 'not_contacted'
  },
  {
    id: '7',
    name: 'Dewsall Court',
    location: 'Hereford, Herefordshire',
    city: 'Herefordshire',
    capacity: 120,
    pricing: { min: 9000, max: 16000, description: '£9,000 - £16,000 (exclusive use)' },
    hasAccommodation: true,
    accommodationRooms: 15,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Exclusive use', 'Licensed for ceremonies', 'Walled garden', 'Parking', 'Bridal suite', 'Lake'],
    aesthetic: ['manor', 'garden', 'traditional'],
    notes: 'Elegant Georgian manor with beautiful walled gardens',
    status: 'not_contacted'
  },
  {
    id: '8',
    name: 'The Gunpowder Store',
    location: 'Portsmouth, Hampshire',
    city: 'Hampshire',
    capacity: 80,
    pricing: { min: 3500, max: 7000, description: '£3,500 - £7,000 (venue hire)' },
    hasAccommodation: false,
    hasOutdoorSpace: true,
    cateringOptions: 'external',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Waterfront', 'Historic building', 'Outdoor space', 'Parking'],
    aesthetic: ['industrial', 'unique', 'waterfront'],
    notes: 'Historic naval building on Priddy\'s Hard with harbour views',
    status: 'not_contacted'
  },
  {
    id: '9',
    name: 'Aynhoe Park',
    location: 'Banbury, Oxfordshire',
    city: 'Oxfordshire',
    capacity: 110,
    pricing: { min: 18000, max: 35000, description: '£18,000 - £35,000 (exclusive use)' },
    hasAccommodation: true,
    accommodationRooms: 20,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['halal', 'kosher', 'vegetarian', 'vegan', 'gluten-free'],
    amenities: ['Exclusive use', 'Licensed for ceremonies', 'Unique interiors', 'Orangery', 'Gardens', 'Parking'],
    aesthetic: ['manor', 'luxury', 'quirky'],
    notes: 'Extraordinary 17th-century country house with quirky contemporary interiors',
    status: 'not_contacted'
  },
  {
    id: '10',
    name: 'Fforest Farm',
    location: 'Pembrokeshire, Wales',
    city: 'Pembrokeshire',
    capacity: 90,
    pricing: { min: 6000, max: 12000, description: '£6,000 - £12,000 (exclusive use)' },
    hasAccommodation: true,
    accommodationRooms: 30,
    hasOutdoorSpace: true,
    cateringOptions: 'both',
    cateringTypes: ['vegetarian', 'vegan', 'halal'],
    amenities: ['Exclusive use', 'Geodomes', 'Lake', 'Farm setting', 'Parking', 'Pizza oven'],
    aesthetic: ['rustic', 'outdoor', 'unique'],
    notes: '200-acre farm with geodomes, lakes, and woodland',
    status: 'not_contacted'
  },
  // Adding 40 more venues
  {
    id: '11',
    name: 'Combermere Abbey',
    location: 'Whitchurch, Cheshire',
    city: 'Cheshire',
    capacity: 130,
    pricing: { min: 10000, max: 18000, description: '£10,000 - £18,000' },
    hasAccommodation: true,
    accommodationRooms: 18,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Exclusive use', 'Licensed for ceremonies', 'Lake', 'Gardens', 'Parking'],
    aesthetic: ['manor', 'traditional', 'garden'],
    notes: 'Historic abbey set in 1,000 acres with private lake',
    status: 'not_contacted'
  },
  {
    id: '12',
    name: 'Asylum',
    location: 'London',
    city: 'London',
    capacity: 250,
    pricing: { min: 6000, max: 15000, description: '£6,000 - £15,000' },
    hasAccommodation: false,
    hasOutdoorSpace: false,
    cateringOptions: 'external',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Central location', 'Unique space', 'Bar'],
    aesthetic: ['industrial', 'modern', 'urban'],
    notes: 'Contemporary venue in the heart of London',
    status: 'not_contacted'
  },
  {
    id: '13',
    name: 'Homme House',
    location: 'Herefordshire',
    city: 'Herefordshire',
    capacity: 150,
    pricing: { min: 8000, max: 14000, description: '£8,000 - £14,000' },
    hasAccommodation: true,
    accommodationRooms: 12,
    hasOutdoorSpace: true,
    cateringOptions: 'both',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Exclusive use', 'Licensed for ceremonies', 'Gardens', 'Parking', 'Bridal suite'],
    aesthetic: ['manor', 'garden', 'traditional'],
    notes: 'Elegant country house with beautiful gardens',
    status: 'not_contacted'
  },
  {
    id: '14',
    name: 'Blackwell Grange',
    location: 'Warwickshire',
    city: 'Warwickshire',
    capacity: 100,
    pricing: { min: 7000, max: 13000, description: '£7,000 - £13,000' },
    hasAccommodation: true,
    accommodationRooms: 16,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['halal', 'vegetarian', 'vegan', 'kosher'],
    amenities: ['Exclusive use', 'Licensed for ceremonies', 'Lake', 'Gardens', 'Parking'],
    aesthetic: ['manor', 'garden', 'traditional'],
    notes: 'Beautiful manor house with lake and extensive grounds',
    status: 'not_contacted'
  },
  {
    id: '15',
    name: 'Fazeley Studios',
    location: 'Birmingham',
    city: 'Birmingham',
    capacity: 180,
    pricing: { min: 4000, max: 9000, description: '£4,000 - £9,000' },
    hasAccommodation: false,
    hasOutdoorSpace: true,
    cateringOptions: 'external',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Industrial space', 'Outdoor courtyard', 'Parking', 'Bar'],
    aesthetic: ['industrial', 'modern', 'urban'],
    notes: 'Creative arts venue with industrial charm',
    status: 'not_contacted'
  },
  {
    id: '16',
    name: 'Askham Hall',
    location: 'Cumbria',
    city: 'Cumbria',
    capacity: 70,
    pricing: { min: 8000, max: 15000, description: '£8,000 - £15,000' },
    hasAccommodation: true,
    accommodationRooms: 15,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['vegetarian', 'vegan', 'halal'],
    amenities: ['Exclusive use', 'Licensed for ceremonies', 'Gardens', 'Michelin-starred chef', 'Parking'],
    aesthetic: ['manor', 'traditional', 'luxury'],
    notes: 'Historic manor with award-winning food and beautiful gardens',
    status: 'not_contacted'
  },
  {
    id: '17',
    name: 'The Fig House',
    location: 'Cotswolds',
    city: 'Gloucestershire',
    capacity: 100,
    pricing: { min: 9000, max: 16000, description: '£9,000 - £16,000' },
    hasAccommodation: true,
    accommodationRooms: 10,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Exclusive use', 'Licensed for ceremonies', 'Gardens', 'Pool', 'Parking'],
    aesthetic: ['modern', 'luxury', 'garden'],
    notes: 'Contemporary Cotswold retreat with stunning views',
    status: 'not_contacted'
  },
  {
    id: '18',
    name: 'Paintworks',
    location: 'Bristol',
    city: 'Bristol',
    capacity: 200,
    pricing: { min: 5000, max: 11000, description: '£5,000 - £11,000' },
    hasAccommodation: false,
    hasOutdoorSpace: true,
    cateringOptions: 'external',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Industrial space', 'Outdoor area', 'Parking', 'Central location'],
    aesthetic: ['industrial', 'modern', 'urban'],
    notes: 'Creative quarter venue with flexible spaces',
    status: 'not_contacted'
  },
  {
    id: '19',
    name: 'Brinkburn Priory',
    location: 'Northumberland',
    city: 'Northumberland',
    capacity: 110,
    pricing: { min: 6000, max: 12000, description: '£6,000 - £12,000' },
    hasAccommodation: false,
    hasOutdoorSpace: true,
    cateringOptions: 'external',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Historic building', 'Riverside', 'Gardens', 'Parking'],
    aesthetic: ['traditional', 'historic', 'unique'],
    notes: '12th-century priory in beautiful riverside setting',
    status: 'not_contacted'
  },
  {
    id: '20',
    name: 'The Normans',
    location: 'York',
    city: 'York',
    capacity: 160,
    pricing: { min: 7000, max: 14000, description: '£7,000 - £14,000' },
    hasAccommodation: true,
    accommodationRooms: 20,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['halal', 'kosher', 'vegetarian', 'vegan'],
    amenities: ['Exclusive use', 'Licensed for ceremonies', 'Gardens', 'Parking', 'Bar'],
    aesthetic: ['modern', 'luxury', 'garden'],
    notes: 'Contemporary venue with beautiful gardens near York',
    status: 'not_contacted'
  },
  {
    id: '21',
    name: 'Merriscourt',
    location: 'Cotswolds',
    city: 'Gloucestershire',
    capacity: 140,
    pricing: { min: 12000, max: 22000, description: '£12,000 - £22,000' },
    hasAccommodation: true,
    accommodationRooms: 25,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Exclusive use', 'Licensed for ceremonies', 'Lake', 'Gardens', 'Parking', 'Spa'],
    aesthetic: ['manor', 'luxury', 'garden'],
    notes: 'Stunning Cotswold estate with lake and extensive grounds',
    status: 'not_contacted'
  },
  {
    id: '22',
    name: 'Brighton Bandstand',
    location: 'Brighton',
    city: 'Brighton',
    capacity: 120,
    pricing: { min: 4500, max: 9000, description: '£4,500 - £9,000' },
    hasAccommodation: false,
    hasOutdoorSpace: true,
    cateringOptions: 'external',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Seafront location', 'Iconic building', 'Outdoor space'],
    aesthetic: ['unique', 'outdoor', 'waterfront'],
    notes: 'Iconic Victorian bandstand on Brighton seafront',
    status: 'not_contacted'
  },
  {
    id: '23',
    name: 'Hengrave Hall',
    location: 'Suffolk',
    city: 'Suffolk',
    capacity: 150,
    pricing: { min: 9000, max: 17000, description: '£9,000 - £17,000' },
    hasAccommodation: true,
    accommodationRooms: 70,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['halal', 'vegetarian', 'vegan', 'kosher'],
    amenities: ['Licensed for ceremonies', 'Historic building', 'Gardens', 'Chapel', 'Parking'],
    aesthetic: ['manor', 'traditional', 'historic'],
    notes: '16th-century manor house with stunning architecture',
    status: 'not_contacted'
  },
  {
    id: '24',
    name: 'Camp Katur',
    location: 'North Yorkshire',
    city: 'Yorkshire',
    capacity: 90,
    pricing: { min: 7000, max: 13000, description: '£7,000 - £13,000' },
    hasAccommodation: true,
    accommodationRooms: 40,
    hasOutdoorSpace: true,
    cateringOptions: 'both',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Exclusive use', 'Geodomes', 'Outdoor setting', 'Lake', 'Parking'],
    aesthetic: ['outdoor', 'unique', 'rustic'],
    notes: 'Glamping venue with geodomes and natural beauty',
    status: 'not_contacted'
  },
  {
    id: '25',
    name: 'Iscoyd Park',
    location: 'Shropshire',
    city: 'Shropshire',
    capacity: 110,
    pricing: { min: 10000, max: 18000, description: '£10,000 - £18,000' },
    hasAccommodation: true,
    accommodationRooms: 18,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Exclusive use', 'Licensed for ceremonies', 'Gardens', 'Coach house', 'Parking'],
    aesthetic: ['manor', 'traditional', 'garden'],
    notes: 'Georgian manor with beautiful walled gardens',
    status: 'not_contacted'
  },
  {
    id: '26',
    name: 'The Old Finsbury Town Hall',
    location: 'London',
    city: 'London',
    capacity: 200,
    pricing: { min: 5500, max: 12000, description: '£5,500 - £12,000' },
    hasAccommodation: false,
    hasOutdoorSpace: false,
    cateringOptions: 'external',
    cateringTypes: ['halal', 'kosher', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Historic building', 'Central location', 'Grand hall'],
    aesthetic: ['traditional', 'historic', 'urban'],
    notes: 'Grade II listed town hall with stunning architecture',
    status: 'not_contacted'
  },
  {
    id: '27',
    name: 'Wilderness Reserve',
    location: 'Suffolk',
    city: 'Suffolk',
    capacity: 100,
    pricing: { min: 8000, max: 15000, description: '£8,000 - £15,000' },
    hasAccommodation: true,
    accommodationRooms: 30,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['vegetarian', 'vegan', 'halal'],
    amenities: ['Exclusive use', 'Treehouses', 'Lake', 'Woodland', 'Parking'],
    aesthetic: ['outdoor', 'unique', 'rustic'],
    notes: 'Luxury treehouse and cabin resort in woodland',
    status: 'not_contacted'
  },
  {
    id: '28',
    name: 'Cuttle Brook House',
    location: 'Derbyshire',
    city: 'Derbyshire',
    capacity: 80,
    pricing: { min: 6000, max: 11000, description: '£6,000 - £11,000' },
    hasAccommodation: true,
    accommodationRooms: 10,
    hasOutdoorSpace: true,
    cateringOptions: 'both',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Exclusive use', 'Licensed for ceremonies', 'Gardens', 'Stream', 'Parking'],
    aesthetic: ['rustic', 'garden', 'traditional'],
    notes: 'Charming country house with stream and gardens',
    status: 'not_contacted'
  },
  {
    id: '29',
    name: 'The Bowdon Rooms',
    location: 'Cheshire',
    city: 'Cheshire',
    capacity: 130,
    pricing: { min: 5000, max: 10000, description: '£5,000 - £10,000' },
    hasAccommodation: false,
    hasOutdoorSpace: true,
    cateringOptions: 'external',
    cateringTypes: ['halal', 'vegetarian', 'vegan', 'kosher'],
    amenities: ['Licensed for ceremonies', 'Historic building', 'Gardens', 'Parking'],
    aesthetic: ['traditional', 'historic', 'garden'],
    notes: 'Former courthouse with character and charm',
    status: 'not_contacted'
  },
  {
    id: '30',
    name: 'Langdon Court',
    location: 'Devon',
    city: 'Devon',
    capacity: 120,
    pricing: { min: 8000, max: 15000, description: '£8,000 - £15,000' },
    hasAccommodation: true,
    accommodationRooms: 18,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Exclusive use', 'Licensed for ceremonies', 'Gardens', 'Parking', 'Bridal suite'],
    aesthetic: ['manor', 'traditional', 'garden'],
    notes: 'Medieval manor house with beautiful Devon countryside',
    status: 'not_contacted'
  },
  {
    id: '31',
    name: 'Northbrook Park',
    location: 'Hampshire',
    city: 'Hampshire',
    capacity: 140,
    pricing: { min: 9000, max: 16000, description: '£9,000 - £16,000' },
    hasAccommodation: true,
    accommodationRooms: 14,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Exclusive use', 'Licensed for ceremonies', 'Gardens', 'Lake', 'Parking'],
    aesthetic: ['manor', 'garden', 'traditional'],
    notes: 'Beautiful Georgian manor with extensive grounds',
    status: 'not_contacted'
  },
  {
    id: '32',
    name: 'The Depot',
    location: 'Cardiff',
    city: 'Cardiff',
    capacity: 150,
    pricing: { min: 4000, max: 8500, description: '£4,000 - £8,500' },
    hasAccommodation: false,
    hasOutdoorSpace: true,
    cateringOptions: 'external',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Industrial space', 'Outdoor terrace', 'Parking', 'Bar'],
    aesthetic: ['industrial', 'modern', 'urban'],
    notes: 'Contemporary warehouse venue in Cardiff Bay',
    status: 'not_contacted'
  },
  {
    id: '33',
    name: 'Cambo Estate',
    location: 'Fife, Scotland',
    city: 'Fife',
    capacity: 100,
    pricing: { min: 7000, max: 13000, description: '£7,000 - £13,000' },
    hasAccommodation: true,
    accommodationRooms: 12,
    hasOutdoorSpace: true,
    cateringOptions: 'both',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Exclusive use', 'Licensed for ceremonies', 'Walled garden', 'Parking'],
    aesthetic: ['manor', 'garden', 'traditional'],
    notes: 'Historic Scottish estate with beautiful gardens',
    status: 'not_contacted'
  },
  {
    id: '34',
    name: 'Elsecar Heritage Centre',
    location: 'South Yorkshire',
    city: 'Yorkshire',
    capacity: 120,
    pricing: { min: 3500, max: 7500, description: '£3,500 - £7,500' },
    hasAccommodation: false,
    hasOutdoorSpace: true,
    cateringOptions: 'external',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Historic building', 'Outdoor space', 'Parking', 'Unique'],
    aesthetic: ['industrial', 'historic', 'unique'],
    notes: 'Victorian ironworks and heritage site',
    status: 'not_contacted'
  },
  {
    id: '35',
    name: 'Sezincote',
    location: 'Cotswolds',
    city: 'Gloucestershire',
    capacity: 90,
    pricing: { min: 11000, max: 20000, description: '£11,000 - £20,000' },
    hasAccommodation: false,
    hasOutdoorSpace: true,
    cateringOptions: 'external',
    cateringTypes: ['halal', 'kosher', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Indian-style architecture', 'Gardens', 'Parking', 'Unique'],
    aesthetic: ['unique', 'luxury', 'garden'],
    notes: 'Extraordinary Indian-inspired Regency house',
    status: 'not_contacted'
  },
  {
    id: '36',
    name: 'Stratton Court Barn',
    location: 'Oxfordshire',
    city: 'Oxfordshire',
    capacity: 160,
    pricing: { min: 7500, max: 14000, description: '£7,500 - £14,000' },
    hasAccommodation: false,
    hasOutdoorSpace: true,
    cateringOptions: 'both',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Barn venue', 'Gardens', 'Parking', 'Bridal suite'],
    aesthetic: ['barn', 'rustic', 'garden'],
    notes: 'Beautiful Cotswold stone barn with countryside views',
    status: 'not_contacted'
  },
  {
    id: '37',
    name: 'RSA House',
    location: 'London',
    city: 'London',
    capacity: 180,
    pricing: { min: 6000, max: 13000, description: '£6,000 - £13,000' },
    hasAccommodation: false,
    hasOutdoorSpace: false,
    cateringOptions: 'in-house',
    cateringTypes: ['halal', 'kosher', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Historic building', 'Central London', 'Grand hall'],
    aesthetic: ['traditional', 'historic', 'luxury'],
    notes: '18th-century house in central London',
    status: 'not_contacted'
  },
  {
    id: '38',
    name: 'Blackwater Distillery',
    location: 'County Waterford, Ireland',
    city: 'Waterford',
    capacity: 110,
    pricing: { min: 5500, max: 11000, description: '€5,500 - €11,000' },
    hasAccommodation: false,
    hasOutdoorSpace: true,
    cateringOptions: 'external',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Distillery tours', 'Riverside', 'Parking', 'Unique'],
    aesthetic: ['industrial', 'unique', 'waterfront'],
    notes: 'Working distillery with riverside setting',
    status: 'not_contacted'
  },
  {
    id: '39',
    name: 'Wick Bottom Barn',
    location: 'Sussex',
    city: 'Sussex',
    capacity: 130,
    pricing: { min: 6500, max: 12000, description: '£6,500 - £12,000' },
    hasAccommodation: true,
    accommodationRooms: 8,
    hasOutdoorSpace: true,
    cateringOptions: 'both',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Barn venue', 'Gardens', 'Parking', 'South Downs'],
    aesthetic: ['barn', 'rustic', 'garden'],
    notes: 'Barn venue in the beautiful South Downs',
    status: 'not_contacted'
  },
  {
    id: '40',
    name: 'Beeston Manor',
    location: 'Lancashire',
    city: 'Lancashire',
    capacity: 140,
    pricing: { min: 8000, max: 15000, description: '£8,000 - £15,000' },
    hasAccommodation: true,
    accommodationRooms: 22,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['halal', 'kosher', 'vegetarian', 'vegan'],
    amenities: ['Exclusive use', 'Licensed for ceremonies', 'Gardens', 'Parking', 'Bar'],
    aesthetic: ['manor', 'traditional', 'garden'],
    notes: 'Country manor with beautiful gardens and lake',
    status: 'not_contacted'
  },
  {
    id: '41',
    name: 'Battersea Arts Centre',
    location: 'London',
    city: 'London',
    capacity: 200,
    pricing: { min: 5000, max: 11000, description: '£5,000 - £11,000' },
    hasAccommodation: false,
    hasOutdoorSpace: false,
    cateringOptions: 'external',
    cateringTypes: ['halal', 'vegetarian', 'vegan', 'kosher'],
    amenities: ['Licensed for ceremonies', 'Historic building', 'Multiple spaces', 'Bar'],
    aesthetic: ['traditional', 'urban', 'unique'],
    notes: 'Victorian town hall turned arts centre',
    status: 'not_contacted'
  },
  {
    id: '42',
    name: 'Homme House',
    location: 'Herefordshire',
    city: 'Herefordshire',
    capacity: 150,
    pricing: { min: 8500, max: 15000, description: '£8,500 - £15,000' },
    hasAccommodation: true,
    accommodationRooms: 15,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Exclusive use', 'Licensed for ceremonies', 'River views', 'Gardens', 'Parking'],
    aesthetic: ['manor', 'traditional', 'garden'],
    notes: 'Georgian house on the River Lugg',
    status: 'not_contacted'
  },
  {
    id: '43',
    name: 'Folly Farm Centre',
    location: 'Bristol',
    city: 'Bristol',
    capacity: 120,
    pricing: { min: 6000, max: 12000, description: '£6,000 - £12,000' },
    hasAccommodation: false,
    hasOutdoorSpace: true,
    cateringOptions: 'both',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Barn venue', 'Gardens', 'Parking', 'Farm setting'],
    aesthetic: ['barn', 'rustic', 'outdoor'],
    notes: 'Rural barn venue with countryside charm',
    status: 'not_contacted'
  },
  {
    id: '44',
    name: 'Hornington Manor',
    location: 'York',
    city: 'York',
    capacity: 100,
    pricing: { min: 9000, max: 16000, description: '£9,000 - £16,000' },
    hasAccommodation: true,
    accommodationRooms: 16,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Exclusive use', 'Licensed for ceremonies', 'Gardens', 'Lake', 'Parking'],
    aesthetic: ['manor', 'traditional', 'garden'],
    notes: 'Restored manor house near York',
    status: 'not_contacted'
  },
  {
    id: '45',
    name: 'Village Underground',
    location: 'London',
    city: 'London',
    capacity: 180,
    pricing: { min: 4500, max: 9500, description: '£4,500 - £9,500' },
    hasAccommodation: false,
    hasOutdoorSpace: true,
    cateringOptions: 'external',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Industrial space', 'Rooftop', 'Unique', 'Bar'],
    aesthetic: ['industrial', 'modern', 'urban'],
    notes: 'Iconic venue with tube carriages on the roof',
    status: 'not_contacted'
  },
  {
    id: '46',
    name: 'Pentney Abbey',
    location: 'Norfolk',
    city: 'Norfolk',
    capacity: 140,
    pricing: { min: 7500, max: 14000, description: '£7,500 - £14,000' },
    hasAccommodation: true,
    accommodationRooms: 20,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Abbey ruins', 'Gardens', 'Lake', 'Parking'],
    aesthetic: ['historic', 'traditional', 'garden'],
    notes: 'Abbey ruins and gatehouse with beautiful grounds',
    status: 'not_contacted'
  },
  {
    id: '47',
    name: 'Stone Barn',
    location: 'Cotswolds',
    city: 'Gloucestershire',
    capacity: 150,
    pricing: { min: 8000, max: 15000, description: '£8,000 - £15,000' },
    hasAccommodation: true,
    accommodationRooms: 10,
    hasOutdoorSpace: true,
    cateringOptions: 'both',
    cateringTypes: ['halal', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Barn venue', 'Gardens', 'Parking', 'Bridal cottage'],
    aesthetic: ['barn', 'rustic', 'garden'],
    notes: 'Cotswold stone barn with beautiful gardens',
    status: 'not_contacted'
  },
  {
    id: '48',
    name: 'The Old Marylebone Town Hall',
    location: 'London',
    city: 'London',
    capacity: 100,
    pricing: { min: 4000, max: 8500, description: '£4,000 - £8,500' },
    hasAccommodation: false,
    hasOutdoorSpace: false,
    cateringOptions: 'external',
    cateringTypes: ['halal', 'kosher', 'vegetarian', 'vegan'],
    amenities: ['Licensed for ceremonies', 'Historic building', 'Central London', 'Iconic'],
    aesthetic: ['traditional', 'historic', 'urban'],
    notes: 'Iconic Edwardian town hall where Paul McCartney married',
    status: 'not_contacted'
  },
  {
    id: '49',
    name: 'Porthilly Farm',
    location: 'Cornwall',
    city: 'Cornwall',
    capacity: 90,
    pricing: { min: 7000, max: 13000, description: '£7,000 - £13,000' },
    hasAccommodation: true,
    accommodationRooms: 25,
    hasOutdoorSpace: true,
    cateringOptions: 'both',
    cateringTypes: ['vegetarian', 'vegan', 'halal'],
    amenities: ['Exclusive use', 'Beach access', 'Farm setting', 'Parking', 'Unique'],
    aesthetic: ['outdoor', 'unique', 'waterfront'],
    notes: 'Farm venue with beach access and estuary views',
    status: 'not_contacted'
  },
  {
    id: '50',
    name: 'Great Tythe Barn',
    location: 'Gloucestershire',
    city: 'Gloucestershire',
    capacity: 160,
    pricing: { min: 8500, max: 16000, description: '£8,500 - £16,000' },
    hasAccommodation: false,
    hasOutdoorSpace: true,
    cateringOptions: 'in-house',
    cateringTypes: ['halal', 'vegetarian', 'vegan', 'kosher'],
    amenities: ['Licensed for ceremonies', 'Medieval barn', 'Gardens', 'Parking'],
    aesthetic: ['barn', 'traditional', 'historic'],
    notes: '15th-century Cotswold stone barn',
    status: 'not_contacted'
  }
];

export function getAllVenues(): Venue[] {
  return MOCK_VENUES;
}

export function getVenueById(id: string): Venue | undefined {
  return MOCK_VENUES.find(v => v.id === id);
}

export function updateVenueStatus(
  id: string,
  status: Venue['status'],
  responseData?: any
): Venue | undefined {
  const venue = MOCK_VENUES.find(v => v.id === id);
  if (venue) {
    venue.status = status;
    venue.lastUpdated = new Date();
    if (responseData) {
      venue.responseData = responseData;
    }
  }
  return venue;
}
